---
- apt_key: id=9DA31620334BD75D9DCB49F368818C72E52529D4 keyserver="keyserver.ubuntu.com"

- apt_repository: repo="deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main"

- apt: name=mongodb-org-server

- apt: name=mongodb-org-mongos

- apt: name=mongodb-org-shell

- apt: name=mongodb-org-tools

- service:
    name: mongod
    state: stopped

- file:
    state=directory
    owner=mongodb
    group=mongodb
    mode="u=rwx,g=rwx,o=rx"
    recurse=yes
    path="{{ mongodb_db_path }}"

# Line from /etc/mongod.conf
# dbPath: /var/lib/mongodb
- lineinfile:
    dest: /etc/mongod.conf
    regexp: "dbPath:"
    line: "  dbPath: {{ mongodb_db_path }}"

- service:
    name: mongod
    enabled: yes
    state: started

#- copy: dest=/etc/init.d/disable-transparent-hugepages
#        src=files/disable-transparent-hugepages
#        mode=0755
#
#- service: name=disable-transparent-hugepages
#           state=started
#           enabled=yes
