---
- apt_key: url=https://packages.grafana.com/gpg.key

- apt_repository: repo="deb https://packages.grafana.com/oss/deb stable main"

- apt: name=grafana

- service:
    name: grafana-server
    enabled: yes
    state: started
