---
- name: Create script that clears all iptables rules
  copy: src=files/iptables_clear.sh
        dest=/sbin/iptables_clear.sh
        mode=0700

- name: /etc/rc.local instruction to clear all iptables rules
  lineinfile: dest=/etc/rc.local
              insertbefore="^exit 0$"
              line=/sbin/iptables_clear.sh

- name: /etc/rc.local instruction to restore iptables rules
  lineinfile: dest=/etc/rc.local
              insertbefore="^exit 0$"
              line="cat /etc/iptables_nat.rules /etc/iptables_filter.rules | iptables-restore"

- name: Create filter rules file
  copy:
    dest: /etc/iptables_filter.rules
    force: no
    content: |
      * filter
      COMMIT

- name: Create nat rules file
  copy:
    dest: /etc/iptables_nat.rules
    force: no
    content: |
      * nat
      COMMIT

- name: Clear iptables rules and apply custom rules
  shell: /sbin/iptables_clear.sh; cat /etc/iptables_nat.rules /etc/iptables_filter.rules | iptables-restore
