---
- name: Create script that clears all iptables rules
  copy:
    dest: /sbin/iptables_clear.sh
    mode: 0700
    content: |
      #!/bin/bash
      iptables -F \
      & iptables -X \
      & iptables -t nat -F \
      & iptables -t nat -X \
      & iptables -t mangle -F \
      & iptables -t mangle -X \
      & iptables -P INPUT ACCEPT \
      & iptables -P FORWARD ACCEPT \
      & iptables -P OUTPUT ACCEPT
      exit

- copy:
    dest: /sbin/iptables_reload.sh
    mode: 0700
    content: |
      #!/bin/bash
      /sbin/iptables_clear.sh & cat /etc/iptables_nat.rules /etc/iptables_filter.rules | iptables-restore
      exit

- name: /etc/rc.local instruction to clear all iptables rules
  lineinfile: dest=/etc/rc.local
              insertbefore="^exit 0$"
              line=/sbin/iptables_clear.sh

- name: /etc/rc.local instruction to restore iptables rules
  lineinfile: dest=/etc/rc.local
              insertbefore="^exit 0$"
              line="cat /etc/iptables_nat.rules /etc/iptables_filter.rules | iptables-restore"

- name: Create filter rules file
  copy:
    dest: /etc/iptables_filter.rules
    force: no
    content: |
      * filter
      COMMIT

- name: Create nat rules file
  copy:
    dest: /etc/iptables_nat.rules
    force: no
    content: |
      * nat
      COMMIT

- name: Clear iptables rules and apply custom rules
  shell: /sbin/iptables_reload.sh
