---
- apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- apt:
    name: apt-transport-https

- copy:
    content: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    dest: /etc/apt/sources.list.d/elastic-7.x.list
  register: test_conf

- apt:
    update_cache: yes
  when: test_conf.changed
