---
- name: Setup APT sources
  copy: src=files/sources.list
        dest=/etc/apt/sources.list

- name: Disable installing suggested APT packages
  copy: content="APT::Install-Suggested \"false\";" dest=/etc/apt/apt.conf.d/07custom

- name: Remove deprecated file
  file: path=/etc/apt/preferences.d/01custom state=absent

- name: Setup apt testing preferences file
  copy: src=roles/apt_testing/files/01testing
        dest=/etc/apt/preferences.d/01testing

- name: Remove apt stable preferences file
  file: dest=/etc/apt/preferences.d/01stable
        state=absent

- name: Update apt cache
  apt: update_cache=yes

- name: Fix apt errors
  shell: apt-get -yf install

- name: Upgrade APT packages
  apt: upgrade=dist
