---
- name: Instal Debian (non-ubuntu) staff
  apt: name={{ item }}
  with_items:
    - python-pip
    - python-crypto
    - firmware-linux-nonfree
    - python3-pyqt4
  when: ansible_distribution == "Debian"

- name: Install common stuff
  apt: name={{ item }}
  with_items:
    #- exim4
    #- bind9-host
    - autoconf
    - apache2-utils
    - aptitude
    - curl
    - debconf-utils
    - conntrack
    - g++
    - gcc
    - geoip-database
    - gettext
    - git-core
    - iftop
    - iotop
    - less
    - libc-ares-dev
    - libcurl4-openssl-dev # build pycurl from source
    - libfreetype6-dev # to build PIL from source
    - libjpeg-dev # to build PIL from source
    - libmemcached-dev
    - libmariadb-dev # to build mysql driver from source
    - libssl-dev
    - libxml2-dev # to build lxml from source
    - libxslt1-dev
    - lshw
    - make
    - mercurial
    #- nfs-common
    - numactl
    - openvpn
    - perl
    - sshfs
    - lvm2
    #- perl-base
    #- perl-modules
    - pigz
    - psmisc
    - python
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python-dev
    - python-setuptools
    - screen
    - subversion
    - sudo
    - unrar
    - unzip
    - vim
    - vim-nox
    - whois
    - tcpdump
    - libgeoip-dev
    - strace
    - wget
    - dnsutils
    - ethtool
    - libffi-dev
    - bc
    - xfsprogs
    - tor
    - apparmor
    - p7zip-full
    - rsync
    - jq
