---
- apt:
    name: certbot

# is --allow-subset-of-names required?
- replace:
    dest: /etc/cron.d/certbot
    regexp: "certbot -q renew$"
    replace: "certbot -q renew --allow-subset-of-names"

# is --allow-subset-of-names required?
- replace:
    dest: /lib/systemd/system/certbot.service
    regexp: "^ExecStart=/usr/bin/certbot -q renew$"
    replace: "ExecStart=/usr/bin/certbot -q renew --allow-subset-of-names"

- copy:
    dest: /etc/letsencrypt/cli.ini
    content: |
      authenticator = webroot
      webroot-path = /web
      post-hook = service nginx reload
      text = True
