---
- name: Add Java Repo APT key
  #apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=C2518248EEA14886
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA8CACC073C3DB2A

- name: Add Java Repo
  #apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main'
  apt_repository: repo='deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main'
                  state=present

- apt:
    update_cache: yes

- name: Accept Java License
  debconf: name='oracle-java15-installer'
           question='shared/accepted-oracle-license-v1-2'
           value='true'
           vtype='select'

- apt:
    name=oracle-java15-installer
    state=latest

- apt:
    name=oracle-java15-set-default
    state=latest
