---
- apt_key:
    url: https://download.docker.com/linux/debian/gpg

- apt_repository:
    repo: "deb https://download.docker.com/linux/debian stretch stable"
    update_cache: yes

- apt:
    name: docker-ce

- apt:
    name: docker-ce-cli

- name: Fix broken ExecStart
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: ^\\1$
    line: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock 

- lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: ^(ExecStart=/usr/bin/dockerd.*)--iptables=false
    line: \1
    backrefs: yes

- systemd:
    name: docker
    daemon_reload: yes
    state: restarted

- user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- pip:
    executable: pip3
    name: docker
