---
- apt_key:
    url: https://download.docker.com/linux/debian/gpg

- apt_repository:
    repo: "deb https://download.docker.com/linux/debian stretch stable"
    update_cache: yes

- apt:
    name: docker-ce

- apt:
    name: docker-ce-cli

- lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: ^(ExecStart=/usr/bin/dockerd.*)--iptables=false
    line: \1

- service:
    name: docker
    state: restarted

- user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- pip:
    name: docker
