---
- apt_key:
    url: https://download.docker.com/linux/debian/gpg

- apt_repository:
    repo: "deb https://download.docker.com/linux/debian stretch stable"
    update_cache: yes

- apt:
    name: docker-ce

- apt:
    name: docker-ce-cli

- lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: ^ExecStart=/usr/bin/dockerd
    line: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --iptables=false

- service:
    name: docker
    state: restarted

- blockinfile:
    dest: /etc/iptables_nat.rules
    marker: "# {mark} docker"
    insertafter: \* nat
    block: |
      -N DOCKER
      -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
      -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
      -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
      -A DOCKER -i docker0 -j RETURN

- blockinfile:
    dest: /etc/iptables_filter.rules
    marker: "# {mark} docker"
    insertafter: \* filter
    block: |
      -N DOCKER
      -N DOCKER-USER
      -N DOCKER-ISOLATION-STAGE-1
      -N DOCKER-ISOLATION-STAGE-2
      -A FORWARD -j DOCKER-USER
      -A FORWARD -j DOCKER-ISOLATION-STAGE-1
      -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A FORWARD -o docker0 -j DOCKER
      -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
      -A FORWARD -i docker0 -o docker0 -j ACCEPT
      -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
      -A DOCKER-ISOLATION-STAGE-1 -j RETURN
      -A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
      -A DOCKER-ISOLATION-STAGE-2 -j RETURN
      -A DOCKER-USER -j RETURN


- shell: /sbin/iptables_reload.sh

- user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
- pip:
    name: docker
