---
- pam_limits: domain=* limit_type=soft limit_item=nofile value=524288
- pam_limits: domain=* limit_type=hard limit_item=nofile value=524288
- pam_limits: domain=root limit_type=soft limit_item=nofile value=524288
- pam_limits: domain=root limit_type=hard limit_item=nofile value=524288

# Needs to apply /etc/security/limits.conf to logged in users
- lineinfile: dest=/etc/pam.d/common-session
             line="session required pam_limits.so"
 
# Needs to apply /etc/security/limits.conf to new processes
- lineinfile: dest=/etc/pam.d/common-session-noninteractive
             line="session required pam_limits.so"
