---
- name: Add google chrome repository
  apt_repository: filename=google-chrome
                  repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

- name: Add google repo APT key
  apt_key: url="https://dl.google.com/linux/linux_signing_key.pub"

- name: Update APT cache
  apt: update_cache=yes

- name: Install xvfb
  apt: name=xvfb

#- apt: name=libgconf-2-4

- name: Install google chrome
  apt: name=google-chrome-stable
